# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

blmC <- function(sims, y, X, b0, B0inv, sigma2, c0 = .1, d0 = .1) {
    .Call('learnMCMC_blmC', PACKAGE = 'learnMCMC', sims, y, X, b0, B0inv, sigma2, c0, d0)
}

rtnormInv <- function(lower = -5, upper = 5, mean = 0, sd = 1) {
    .Call('learnMCMC_rtnormInv', PACKAGE = 'learnMCMC', lower, upper, mean, sd)
}

